[package]
name = "markdown_converter"
description = "A simple html to markdown converter and flavored markdown to discord markdown converter"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.4"
